package by.timeslowly.duacan_delight.registry;

import by.timeslowly.duacan_delight.Duacan_delight;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class DDCreativeTabs {
    public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, Duacan_delight.MOD_ID);
    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> DuaCanDelight = REGISTRY.register("duacan_delight",
            () -> CreativeModeTab.builder().title(Component.translatable("item_group.duacan_delight.duacan_delight"))
                    .icon(() -> new ItemStack(DDItems.GODONGGUI.get()))
                    .displayItems((parameters, tabData) -> {

                tabData.accept(DDItems.GODONGGUI.get());
                tabData.accept(DDItems.SMALLINTESTINE_TOFU_SOUP.get());
                tabData.accept(DDItems.WULING_ROAST_RABBIT.get());
                tabData.accept(DDItems.SMALLINTESTINE_KUCAI_SOUP.get());
                tabData.accept(DDItems.ZHUJIOAGANFAN.get());
                tabData.accept(DDItems.XIANFAN.get());
                tabData.accept(DDItems.LAVER_PORK_SOUP.get());
                tabData.accept(DDItems.PIG_LIVER_SOUP.get());
                tabData.accept(DDItems.BEEF_SOUP.get());
                tabData.accept(DDItems.COOKED_MIFEN.get());
                tabData.accept(DDItems.RUSSULA_MIANXIAN.get());
                tabData.accept(DDItems.CUMA.get());
                tabData.accept(DDItems.EAJIAN.get());
                tabData.accept(DDItems.EAJIAN_TOMATO_SAUCE.get());
                tabData.accept(DDItems.FRIED_LAGER_INTESTINE_WITH_SUANCAI.get());
                tabData.accept(DDItems.MIDENGGUI.get());
                tabData.accept(DDItems.CHICKEN_CONSOMME.get());
                tabData.accept(DDItems.CHICKEN_CONSOMME_MIANXIAN.get());
                tabData.accept(DDItems.CLAM_TOFU_SOUP.get());
                tabData.accept(DDItems.GUOJIAO.get());
                tabData.accept(DDItems.CAOGUO.get());
                tabData.accept(DDItems.FENSI_STEAMED_CRAB.get());
                tabData.accept(DDItems.FENSI_STEAMED_CLAWSTER.get());
                tabData.accept(DDItems.ROASTED_MINCED_GARLIC_OYSTER.get());
                tabData.accept(DDItems.BRAISED_BAMBOOSHOOT_WITH_SUANCAI.get());
                tabData.accept(DDItems.XIFAN.get());
                tabData.accept(DDItems.SWEET_POTATO_PORRIDGE.get());
                tabData.accept(DDItems.ROUSONGXIFAN.get());
                tabData.accept(DDItems.XIFAN_WITH_MUSHROOM_MEAT_SAUCE.get());
                tabData.accept(DDItems.KELP_TOFU_SOUP.get());
                tabData.accept(DDItems.LAVER_EGG_SOUP.get());
                tabData.accept(DDItems.SEAWEED_SALAD.get());
                tabData.accept(DDItems.ROUSONG.get());
                tabData.accept(DDItems.YOUZHA.get());
                tabData.accept(DDItems.ANGLENG.get());
                tabData.accept(DDItems.FRIED_TOFU.get());
                tabData.accept(DDItems.XIANCAODONG.get());
                tabData.accept(DDItems.SIGUOTENG.get());
                tabData.accept(DDItems.MUSHROOM_MEAT_SAUCE.get());
                tabData.accept(DDItems.PEANUTS_MILK.get());
                tabData.accept(DDItems.VEGETABLE_JUICE.get());
                tabData.accept(DDItems.OIL_CUT_WHEAT_TEA.get());
                tabData.accept(DDItems.RAW_CUMA.get());
                tabData.accept(DDItems.ZHUAFEN_MINCED_BEEF.get());
                tabData.accept(DDItems.ZHUAFEN_PIG_LIVER.get());
                tabData.accept(DDItems.RAW_EAJIAN.get());
                tabData.accept(DDItems.MINCED_GARLIC_SAUCE.get());
                tabData.accept(DDItems.ZHUJIAO.get());
                tabData.accept(DDItems.SLICED_PIG_LIVER.get());
                tabData.accept(DDItems.PIG_SMALL_INTESTINE.get());
                tabData.accept(DDItems.PIG_LARGE_INTESTINE.get());
                tabData.accept(DDItems.GAICAI.get());
                tabData.accept(DDItems.GAICAI_LEAF.get());
                tabData.accept(DDItems.SUANCAI.get());
                tabData.accept(DDItems.DRIED_SUANCAI.get());
                tabData.accept(DDItems.SLICED_SUANCAI.get());
                tabData.accept(DDItems.KUCAI.get());
                tabData.accept(DDItems.GAICAI_SEEDS.get());
                tabData.accept(DDItems.XIANCAO_STEM.get());
                tabData.accept(DDItems.XIANCAO_LEAF.get());
                tabData.accept(DDItems.KUCAI_SEEDS.get());
                tabData.accept(DDItems.TREMELLA.get());
                tabData.accept(DDBlocks.LAVER_HEAD.get().asItem());
                tabData.accept(DDItems.DRIED_LAVER.get());
                tabData.accept(DDItems.TREMELLA_SPORE.get());
                tabData.accept(DDItems.ADAZI.get());
                tabData.accept(DDBlocks.CHINESE_WOLFBERRY_TREESAPLING.get().asItem());
                tabData.accept(DDBlocks.CHINESE_WOLFBERRY_LEAVES.get().asItem());
                tabData.accept(DDItems.CHINESE_WOLFBERRY.get());
                tabData.accept(DDItems.YIMI.get());
                tabData.accept(DDItems.LOTUS_SEEDS.get());
                tabData.accept(DDItems.CHOPPED_GREENONION.get());
                tabData.accept(DDItems.SLICED_SWEET_POTATO.get());
                tabData.accept(DDItems.WETRICE.get());
                tabData.accept(DDItems.DIGUA_POWDER_DOUGH.get());
                tabData.accept(DDItems.BOILED_DIGUA_POWDER_DOUGH.get());
                tabData.accept(DDItems.FENSI.get());
                tabData.accept(DDItems.WET_FENSI.get());
                tabData.accept(DDItems.WET_MIANXIAN.get());
                tabData.accept(DDItems.MIANXIAN.get());
                tabData.accept(DDItems.XIANCAO_POWDER.get());
                tabData.accept(DDItems.RAW_CAOGUO.get());
                tabData.accept(DDItems.BAMBOO_SHOOT.get());
                tabData.accept(DDItems.SLICED_BAMBOOSHOOT.get());
                tabData.accept(DDItems.SLICED_ZHUJIAO.get());
                tabData.accept(DDItems.DRIED_SLICED_BAMBOOSHOOT.get());
                tabData.accept(DDItems.MONASCUS.get());
                tabData.accept(DDItems.FRIED_GRATED_GARLIC.get());
                tabData.accept(DDItems.TOFU.get());
                tabData.accept(DDItems.CHINESE_ANGELICA.get());
                tabData.accept(DDItems.CASSIA_SEED.get());
                tabData.accept(DDItems.FIRED_CASSIA_SEED.get());
                tabData.accept(DDItems.WET_MIFEN_DOUGH.get());
                tabData.accept(DDItems.COOKED_MIFEN_DOUGH.get());
                tabData.accept(DDItems.WET_MIFEN.get());
                tabData.accept(DDItems.MIFEN.get());
                tabData.accept(DDItems.RAW_GUOJIAO.get());
                tabData.accept(DDItems.RICE_MILK.get());
                tabData.accept(DDItems.OYSTER.get());
                tabData.accept(DDItems.OYSTER_SHELL.get());
                tabData.accept(DDItems.RAW_MINCED_GARLIC_OYSTER.get());
                tabData.accept(DDItems.RAW_OYSTER_MEAT.get());
                tabData.accept(DDItems.IRON_CAN.get());
                tabData.accept(DDItems.OPENED_IRON_CAN.get());
                tabData.accept(DDItems.RICE_WINE.get());
                tabData.accept(DDItems.CHOPSTICKS.get());
                tabData.accept(DDItems.BOTTLE_OF_TEAOIL.get());
                tabData.accept(DDItems.I_GRASS_JUICE_BUCKET.get());
                tabData.accept(DDItems.SOYBEAN_MILK_FLUID_BUCKET.get());
                tabData.accept(DDItems.TEAOIL_FLUID_BUCKET.get());
                tabData.accept(DDBlocks.LAVER_CRATE.get().asItem());
                tabData.accept(DDBlocks.GAICAI_CRATE.get().asItem());
                tabData.accept(DDBlocks.KUCAI_CRATE.get().asItem());
                tabData.accept(DDBlocks.OYSTER_BARREL.get().asItem());
                tabData.accept(DDBlocks.YIMI_BAG.get().asItem());
                tabData.accept(DDBlocks.LOTUS_SEEDS_BAG.get().asItem());
                tabData.accept(DDBlocks.CHINESE_WOLFBERRY_BAG.get().asItem());
                tabData.accept(DDBlocks.BAMBOO_SHOOT_CRATE.get().asItem());
                tabData.accept(DDBlocks.MONASCUS_BAG.get().asItem());
                tabData.accept(DDBlocks.XIANCAO_POWDER_BAG.get().asItem());
                tabData.accept(DDBlocks.TREMELLA_BAG.get().asItem());

            }).build());
}
